### ISSUE TITLE
Multi-byte support?

### ISSUE THREAD

**Issue by mnpenner** [soatok/left-pad#2]
This doesn't work on multi-byte strings.

**Comment by soatok** [comment]
Oh no. I'll rectify that immediately.

**Comment by soatok** [comment]
Can you confirm that this works? https://github.com/soatok/left-pad/commit/4a50559f2486e21c892b7406faa19cded2ec4db4

**Comment by mnpenner** [comment]
``` php
public function testUtf8() {
    $this->assertSame(
        '██x',
        left_pad('x', 3, '█', 'utf8')
    );
}
```

Yeah... it works.

**Comment by soatok** [comment]
:+1:
